### ISSUE TITLE
Ordering of the badges 

### ISSUE THREAD

**Issue by AdarshRawat1** [OpenCodeEra/GitHub-Profile-Achievements#1]
Order the badges from 'Very Easy' to 'Easy' to 'Medium' and finally  'Hard' in  "Obtainable Achievements" section.

**Comment by rakshit0960** [comment]
are you working on it?

**Comment by AdarshRawat1** [comment]
@rakshit0960 This issue is open for contribution. I am not working on it right now. You can open a PR and mention this issue.

**Comment by rakshit0960** [comment]
@AdarshRawat1 I have made this pull request #4

**Comment by AdarshRawat1** [comment]
> @AdarshRawat1 I have made this pull request #4

@rakshit0960 I'll check 🙌
p.s. You can also mention the issue in PR .
